name: onesignal_flutter
description: OneSignal is a free push notification service for mobile apps. This plugin makes it easy to integrate your flutter app with OneSignal
version: 3.4.2
author: Brad Hesse <brad@onesignal.com>, Josh Kasten <josh@onesignal.com>
homepage: https://github.com/OneSignal/OneSignal-Flutter-SDK

flutter:
  plugin:
    platforms:
      android:
        package: com.onesignal.flutter
        pluginClass: OneSignalPlugin
      ios:
        pluginClass: OneSignalPlugin

dependencies:
  webview_flutter_android: ^2.8.0
  webview_flutter_platform_interface: ^1.9.3
  webview_flutter_wkwebview: ^2.7.0
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.1.5
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.10.0'
